
GET http://localhost:3001/api/persons/4


###
GET http://localhost:3001/
###
DELETE http://localhost:3001/api/persons/8

###
POST http://localhost:3001/api/persons/ 
Content-Type: application/json

{
    "name": "dasdd",
    "number": "5442131"
}